### ISSUE TITLE
Compile error with ls-files -i option

### ISSUE THREAD

**Issue by DaddyChucky** [abelfodil/inf1900-grader#33]
**Bug:**
Line 60 in grader.py, must specify option -o or -c along with -i for git ls-files

**Fix:**
Replace:
return Repo(repo_path).git.ls_files("-i", f"--exclude-from={bad_files_list}", *subdirectories)

with:
return Repo(repo_path).git.ls_files("-ico", f"--exclude-from={bad_files_list}", *subdirectories)
**_(multiple fixes exist)_**

**Comment by abelfodil** [comment]
Salut Charles! 

Peux-tu stp envoyer une pull request?

Merci pour ton temps!

**Comment by DaddyChucky** [comment]
Ça me ferait plaisir d'en faire une, mais je n'ai pas les droits d'accès. Serait-ce possible de me mettre dev ou maintainer sur le repo ? Merci :)
